version: '3.3'

networks:
  core:
    external: true

services:
  code-server:
    image: 'codercom/code-server:latest'
    container_name: code-server
    expose:
      - 8080
    volumes:
      - '$HOME/.config/code-server:/home/coder/.config/code-server'
      - '$PWD/../:/home/coder/project'
      - '$HOME/.gitconfig:/home/coder/.gitconfig'
      - '$HOME/.git-credentials:/home/coder/.git-credentials'
    environment:
      - DOCKER_USER=$USER
      - TZ
    networks:
      - core
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code-server.entrypoints=websecure"
      - "traefik.http.routers.code-server.rule=Host(`$HOSTNAME`) && PathPrefix(`/code`)"
      - "traefik.http.services.code-server.loadbalancer.server.port=8080"
      - "traefik.http.routers.code-server.middlewares=authelia@docker"
      - "traefik.http.routers.code-server.middlewares=code-server-stripprefix"
      - "traefik.http.middlewares.code-server-stripprefix.stripprefix.prefixes=/code"
    command: --auth none --user-data-dir /home/coder/.config/code-server /home/coder/project