global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9090']
      labels:
        host: '${PROMETHEUS_CL_HOST_1}'

  - job_name: 'node'
    scheme: https
    static_configs:
    - targets: ['${PROMETHEUS_CL_HOSTNAME_1}']
      labels:
        host: '${PROMETHEUS_CL_HOST_1}'
    - targets: ['${PROMETHEUS_CL_HOSTNAME_2}']
      labels:
        host: '${PROMETHEUS_CL_HOST_2}'
    - targets: ['${PROMETHEUS_CL_HOSTNAME_3}']
      labels:
        host: '${PROMETHEUS_CL_HOST_3}'
    metrics_path: 'node_exporter'
    basic_auth:
      username: '${NODE_EXPORTER_USER}'
      password: '${NODE_EXPORTER_PASS}'

  - job_name: 'cadvisor'
    scheme: https
    static_configs:
    - targets: ['${PROMETHEUS_CL_HOSTNAME_1}']
      labels:
        host: '${PROMETHEUS_CL_HOST_1}'
    - targets: ['${PROMETHEUS_CL_HOSTNAME_2}']
      labels:
        host: '${PROMETHEUS_CL_HOST_2}'
    - targets: ['${PROMETHEUS_CL_HOSTNAME_3}']
      labels:
        host: '${PROMETHEUS_CL_HOST_3}'
    metrics_path: 'cadvisor/metrics'
    basic_auth:
      username: '${CADVISOR_USER}'
      password: '${CADVISOR_PASS}'
