global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9090']
      labels:
        host: '${HOST}'

  - job_name: 'node'
    scheme: https
    static_configs:
    - targets: ['${HOSTNAME}']
      labels:
        host: '${HOST}'
    - targets: ['${HOSTNAME_2}']
      labels:
        host: '${HOST_2}'
    metrics_path: 'node_exporter'
    basic_auth:
      username: '${NODE_EXPORTER_USER}'
      password: '${NODE_EXPORTER_PASS}'

  - job_name: 'cadvisor'
    scheme: https
    static_configs:
    - targets: ['${HOSTNAME}']
      labels:
        host: '${HOST}'
    - targets: ['${HOSTNAME_2}']
      labels:
        host: '${HOST_2}'
    metrics_path: 'cadvisor/metrics'
    basic_auth:
      username: '${CADVISOR_USER}'
      password: '${CADVISOR_PASS}'
