version: "3"

networks:
  core:
    external: true
  redis:
    name: redis

services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - ./config/authelia.yml:/config/authelia.yml:ro
      - ../data/authelia:/data
    networks:
      - core
      - redis
    command: --config /config/authelia.yml
    environment:
      - AUTHELIA_JWT_SECRET
      - AUTHELIA_DEFAULT_REDIRECTION_URL
      - AUTHELIA_SESSION_DOMAIN
      - AUTHELIA_SESSION_SECRET
      - AUTHELIA_STORAGE_ENCRYPTION_KEY
      - AUTHELIA_NOTIFIER_SMTP_HOST
      - AUTHELIA_NOTIFIER_SMTP_USERNAME
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD
      - AUTHELIA_NOTIFIER_SMTP_SENDER
      - AUTHELIA_NOTIFIER_SMTP_TLS_SERVER_NAME
      - TZ
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=core'
      - 'traefik.http.routers.authelia.rule=Host(`${AUTHELIA_HOSTNAME}`)'
      - 'traefik.http.routers.authelia.entrypoints=websecure'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://${AUTHELIA_HOSTNAME}'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
    ports:
      - 9091:9091
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      disable: true

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - redis
    expose:
      - 6379
    command: redis-server --save 60 1 --loglevel warning
    volumes: 
      - ../data/redis:/data