version: "3"

networks:
# docker network create core
  core:
    external: true

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    networks:
      - core
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ../data/traefik-certs:/etc/traefik-certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TRAEFIK_CERTIFICATESRESOLVERS_letsencrypt_ACME_EMAIL=$CERT_EMAIL
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`$HOSTNAME`)'
      - 'traefik.http.routers.api.entrypoints=websecure'
      - 'traefik.http.routers.api.service=api@internal'
      - 'traefik.http.routers.api.middlewares=authelia@docker'
    restart: unless-stopped

  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - ./config/authelia.yml:/config/authelia.yml:ro
      - ../data/authelia:/data
    networks:
      - core
    command: --config /config/authelia.yml
    environment:
      - AUTHELIA_JWT_SECRET
      - AUTHELIA_DEFAULT_REDIRECTION_URL
      - AUTHELIA_SESSION_DOMAIN
      - AUTHELIA_STORAGE_ENCRYPTION_KEY
      - AUTHELIA_NOTIFIER_SMTP_HOST
      - AUTHELIA_NOTIFIER_SMTP_USERNAME
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD
      - AUTHELIA_NOTIFIER_SMTP_SENDER
      - AUTHELIA_NOTIFIER_SMTP_TLS_SERVER_NAME
      - TZ
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`$HOSTNAME`) && PathPrefix(`/auth`)'
      - 'traefik.http.routers.authelia.entrypoints=websecure'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://$HOSTNAME/auth/'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
    expose:
      - 9091
    restart: unless-stopped
    healthcheck:
      disable: true
