version: "3"

networks:
  loki:
    external: true
  core:
    external: true

services:
  prometheus:
    # image: prom/prometheus:latest
    build: ./prometheus
    container_name: prometheus
    expose:
      - 9090
    networks:
      - loki
    environment:
      - HOST
      - HOSTNAME
      - NODE_EXPORTER_USER
      - NODE_EXPORTER_PASS
      - CADVISOR_USER
      - CADVISOR_PASS
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.env.yml:ro
      - ../data/prometheus:/prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'

  loki:
    image: grafana/loki:2.4.2
    container_name: loki
    volumes:
      - ../data/loki:/loki
      - ./config:/etc/loki
    expose:
      - 3100
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki
      - core
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=core"
      - "traefik.http.routers.loki.entrypoints=websecure"
      - "traefik.http.routers.loki.rule=Host(`$HOSTNAME`) && PathPrefix(`/loki`)"
      - "traefik.http.routers.loki.middlewares=loki"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"
      - "traefik.http.middlewares.loki.basicauth.users=$LOKI_AUTH"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ../data/grafana:/var/lib/grafana
      - ./config:/etc/grafana
    environment:
      - GF_SERVER_DOMAIN=$HOSTNAME
      - GF_SERVER_ROOT_URL=$ROOTURL
    expose:
      - 3000
    restart: unless-stopped
    networks:
      - loki
      - core
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=core"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.rule=Host(`$HOSTNAME`) && PathPrefix(`/grafana`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.middlewares=authelia@docker"
