global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: INFO

accessLog: {}

api:
  dashboard: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
    http:
      tls:
        certResolver: letsencrypt

certificatesResolvers:
  letsencrypt:
    acme:
      storage: /etc/traefik-certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true
