###############################################################
#                   Authelia configuration                    #
###############################################################

#jwt_secret:
#default_redirection_url:
theme: dark

server:
  host: 0.0.0.0
  port: 9091

log:
  level: info

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /data/users_database.yml

access_control:
  default_policy: one_factor

session:
  name: auth_token
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
#  domain: # Should match whatever your root protected domain is
#  secret: # Required when using redis
  redis:
    host: "redis"
    port: 6379

regulation:
  max_retries: 5
  find_time: 120
  ban_time: 300

storage:
#  encryption_key:
  local:
    path: /data/db.sqlite3

notifier:
  smtp:
#    host:
    port: 465
    timeout: 5s
#    username:
#    password:
#    sender:
    subject: "[Authelia] {title}"
    tls:
#      server_name:
      minimum_version: TLS1.2
