version: "3"

networks:
  core:
    external: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    expose:
      - 3001
    volumes:
      - ../data/uptime-kuma:/app/data
    networks:
      - core
    dns:
      - ${WG_GATEWAY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.entrypoints=websecure"
      - "traefik.http.routers.uptime-kuma.rule=Host(`${HOSTNAME_UPTIME_KUMA}`)"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
      # - "traefik.http.routers.uptime-kuma.middlewares=authelia@docker"
    restart: unless-stopped