version: "3"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ
      - SERVERURL=$HOSTNAME
      - SERVERPORT
      - PEERS
      - PEERDNS
      - INTERNAL_SUBNET
    volumes:
      - ../data/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - $SERVERPORT:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
