version: "3"

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ
      - SERVERURL=${HOSTNAME}
      - SERVERPORT
      - PEERS
      - INTERNAL_SUBNET
    volumes:
      - ../data/wireguard:/config
      - /lib/modules:/lib/modules
    network_mode: host
    restart: unless-stopped

# Note: Setup CoreDNS rewrite rule
# Note: Change server port on wg0.conf